/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "kuka.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

kukaVar_t *
initialize_1(void *argp, CLIENT *clnt)
{
	static kukaVar_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INITIALIZE,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

kukaVar_t *
uninitialize_1(void *argp, CLIENT *clnt)
{
	static kukaVar_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UNINITIALIZE,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

kukaVar_t *
getvar_1(kukaVar_t *argp, CLIENT *clnt)
{
	static kukaVar_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETVAR,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) argp,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

kukaVar_t *
setvar_1(kukaVar_t *argp, CLIENT *clnt)
{
	static kukaVar_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SETVAR,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) argp,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

kukaVar_t *
loadmodule_1(char **argp, CLIENT *clnt)
{
	static kukaVar_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LOADMODULE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

kukaVar_t *
unloadmodule_1(void *argp, CLIENT *clnt)
{
	static kukaVar_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UNLOADMODULE,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

kukaVar_t *
getcrosserror_1(void *argp, CLIENT *clnt)
{
	static kukaVar_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETCROSSERROR,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_kukaVar_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
