controller_list:
  - name: fake_arm_controller
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
  - name: fake_gripper_controller
    joints:
      []